title: My Portfolio
description: The portfolio site of Chris Wood - Technical Author and UX Writer
theme: just-the-docs

url: https://chriswood.netlify.app/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
# color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red

  information:
    title: Information
    color: blue

  note:
    title: Note
    color: purple

  tip:
    title: Tip
    color: green
